FROM node:14.15.2
ENV NODE_ENV=production

WORKDIR /
COPY . .

COPY ["package.json", "package-lock.json*", "./"]

RUN npm install
RUN npm audit fix --legacy-peer-deps
RUN npm run build

CMD [ "npm", "start"]
